# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('poll_type', models.CharField(blank=True, max_length=10, null=True)),
                ('overall_rationale', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('rationale', models.TextField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Ballot')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.CharField(max_length=20)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('flair', models.FilePathField(path='E:\\workspace\\rcfbpoll\\rcfbpoll\\staticfiles\\images/full60')),
                ('logo', models.FilePathField(path='E:\\workspace\\rcfbpoll\\rcfbpoll\\staticfiles\\images/fullorig')),
                ('header', models.FilePathField(path='E:\\workspace\\rcfbpoll\\rcfbpoll\\staticfiles\\images/header240')),
                ('conference', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('primary_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Team')),
            ],
        ),
        migrations.CreateModel(
            name='UserSecondaryAffiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.User')),
            ],
        ),
        migrations.AddField(
            model_name='ballotentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Team'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.User'),
        ),
    ]
