# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20160714_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flair',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='team',
            name='header',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(max_length=80),
        ),
    ]
