# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20160714_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='flair',
        ),
        migrations.RemoveField(
            model_name='team',
            name='header',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
