# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20160714_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='use_for_ballot',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=6),
        ),
    ]
