# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20160714_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='handle',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
