# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('close_date',)},
        ),
        migrations.AlterField(
            model_name='ballot',
            name='overall_rationale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
