# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20160727_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotentry',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
