# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20160805_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollPoints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'poll_pollpoints',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='last_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
        ),
    ]
